### PR TITLE
Add jaeger-client module

### PR DESCRIPTION
**Pull request by jpkrohling**
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

## Which problem is this PR solving?
- Providing a module for instrumented applications with the tracer resolver and a module with senders, like `jaeger-thrift`. Having this abstracted under a new module makes it easier to change the sender in the future, or add more dependencies as we need.

## Short description of the changes

Before, this was required:
```xml
        <dependency>
            <groupId>io.jaegertracing</groupId>
            <artifactId>jaeger-thrift</artifactId>
            <version>0.30.0</version>
        </dependency>
        <dependency>
            <groupId>io.jaegertracing</groupId>
            <artifactId>jaeger-tracerresolver</artifactId>
            <version>0.30.0</version>
        </dependency>
```

Which results in:

```
[INFO] +- io.jaegertracing:jaeger-thrift:jar:0.30.0:compile
[INFO] |  \- io.jaegertracing:jaeger-core:jar:0.30.0:compile
[INFO] |     +- io.opentracing:opentracing-api:jar:0.31.0:compile
[INFO] |     +- io.opentracing:opentracing-util:jar:0.31.0:compile
[INFO] |     +- com.google.code.gson:gson:jar:2.8.2:compile
[INFO] |     \- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] +- io.jaegertracing:jaeger-tracerresolver:jar:0.30.0:compile
[INFO] |  \- io.opentracing.contrib:opentracing-tracerresolver:jar:0.1.4:compile
```

Now:

```xml
        <dependency>
            <groupId>io.jaegertracing</groupId>
            <artifactId>jaeger-client</artifactId>
            <version>0.30.1-SNAPSHOT</version>
        </dependency>
```

Which results in:
```
[INFO] +- io.jaegertracing:jaeger-client:jar:0.30.1-SNAPSHOT:compile
[INFO] |  +- io.jaegertracing:jaeger-thrift:jar:0.30.1-SNAPSHOT:compile
[INFO] |  +- io.jaegertracing:jaeger-tracerresolver:jar:0.30.1-SNAPSHOT:compile
[INFO] |  |  \- io.opentracing.contrib:opentracing-tracerresolver:jar:0.1.4:compile
[INFO] |  \- io.jaegertracing:jaeger-core:jar:0.30.1-SNAPSHOT:compile
[INFO] |     +- io.opentracing:opentracing-api:jar:0.31.0:compile
[INFO] |     +- io.opentracing:opentracing-util:jar:0.31.0:compile
[INFO] |     +- com.google.code.gson:gson:jar:2.8.2:compile
[INFO] |     \- org.slf4j:slf4j-api:jar:1.7.25:compile
```

### CODE REVIEW

**Comment by jpkrohling** [comment]
@objectiser could you please check if this would cover your use case?

**Comment by objectiser** [comment]
@jpkrohling Could you update the readme to also refer to this module instead of the `jaeger-thrift`

**Comment by jpkrohling** [comment]
`README` updated

**Comment by jpkrohling** [comment]
To avoid publishing an empty jar (which might not be allowed in some repositories, possibly Sonatype included), @objectiser suggested adding a `Version` class to the new module, which was done in the last commit.

**Pull request merged**
