### PR TITLE
Corrected header name in the java client README

### PR DESCRIPTION
**Pull request by kislayverma**
Corrected the spelling of the header from "operartion-name" to the correct "operation-name"

### CODE REVIEW

**Comment by black-adder** [comment]
thanks for the contribution, can you sign off on all your commits?

**Comment by kislayverma** [comment]
Apologies for missing this. Is there a guidelines page where I can check
out the pre-reqs for contributing?

I have signed the previous commit. Will do so for all further changes.

**Comment by yurishkuro** [comment]
the guidelines are in https://github.com/jaegertracing/jaeger-client-java/blob/master/CONTRIBUTING.md

**Comment by yurishkuro** [comment]
given that this is a small change, might be easier to open another PR based off master with the signed commit

**Comment by kislayverma** [comment]
Sounds right @yurishkuro 

I am closing this PR and will open a another one with a signed commit.

**Pull request closed without merging**
