### PR TITLE
Add sonarqube for code quality analysis

### PR DESCRIPTION
**Pull request by jpkrohling**
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

## Which problem is this PR solving?
- See #439. This PR is required to get started with `sonarqube`, but does *not* include all the pieces to get it working on Travis. For that, someone (@vprithvi?) needs to add the appropriate properties to the Travis project, as per https://docs.travis-ci.com/user/sonarcloud/

## Short description of the changes
- Added the `sonarqube` plugin
- Exclude jaeger-thrift's `gen-java` from the analysis

### CODE REVIEW

**Comment by yurishkuro** [comment]
Looks like someone already created jaegertracing org on sonarcloud

image

**Comment by jpkrohling** [comment]
That would be @vprithvi :-)

**Comment by jpkrohling** [comment]
Ping @vprithvi

**Comment by vprithvi** [comment]
Apologies, I was OOO and away from a computer for the last couple of weeks. I'll add everyone in the github org as members and add the appropriate travis keys

**Comment by vprithvi** [comment]
I've added the travis keys, but I wasn't able to find you on sonarcloud, could you create an account there?
Alternatively, I take could over this PR and add the configs in the `.travis` file

**Comment by jpkrohling** [comment]
My account seems to be "jpkrohling@github" but feel free to take it over :)

**Comment by jpkrohling** [comment]
Unfortunately, I have to pause work on this PR due to other tasks on my queue. 

With this PR, I'm able to get results published to Sonarcloud by running:

```
./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=jaegertracing
```

But I can't get it working on Travis... Also, note that it doesn't seem to be possible to get it working for PRs from contributors ("external" pull requests), only for PRs originated from branches in this repository ("internal" pull requests).

**Pull request closed without merging**
