### PR TITLE
Prepare release 0.33.0

### PR DESCRIPTION
**Pull request by objectiser**
Signed-off-by: Gary Brown <gary@brownuk.com>

### CODE REVIEW

**Comment by objectiser** [comment]
@pavolloffay Tried following the release instructions but it [failed on the maven deploy](https://travis-ci.org/jaegertracing/jaeger-client-java/jobs/468034862). Tried restarting multiple times, but didn't work. I don't appear to have access to the staging repos, so would you be able to finish the release?

**Comment by pavolloffay** [comment]
The release via travis is broken. It has to be done manually. I will release it locally for you now. 

For future please ask release right in sonatype jira https://issues.sonatype.org/browse/OSSRH-34706?jql=text%20~%20%22jaegertracing%22

**Comment by mpetazzoni** [comment]
@pavolloffay Thanks! I'm not seeing 0.33.0 yet in Maven Central. Were you able to publish the release?

**Comment by pavolloffay** [comment]
I have released it this morning. https://repo.maven.apache.org/maven2/io/jaegertracing/jaeger-core/0.33.0/ 

Let us know if there are any issues.

**Comment by mpetazzoni** [comment]
`io.jaegertracing:jaeger-client` still seems to be 0.32.0: https://search.maven.org/search?q=g:io.jaegertracing%20AND%20a:jaeger-client

**Comment by pavolloffay** [comment]
https://github.com/jaegertracing/jaeger-client-java/issues/577

**Pull request merged**
