### PR TITLE
Updated the signing env vars to match the new organization

### PR DESCRIPTION
**Pull request by jpkrohling**
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by yurishkuro** [comment]
Thanks @jpkrohling

**Comment by yurishkuro** [comment]
Doesn't look like it worked 

https://travis-ci.org/jaegertracing/jaeger-client-java/jobs/283295250

`denied: requested access to the resource is denied`

**Comment by jpkrohling** [comment]
This PR is only for the `SIGNING_*` vars, which signs the jar artifacts before uploading them to Nexus. The failure you've seen is about the Docker credentials, but I don't have access to them. 

If nobody has access to the credentials anymore, let me know and I'll figure out a way to get it working again.

**Comment by yurishkuro** [comment]
I do have them, but they are for user `uberbot`. I will create a new user.

**Comment by yurishkuro** [comment]
done

**Pull request merged**
