### PR TITLE
TRACER-#369: Added a logger property logr which will handle the excep…

### PR DESCRIPTION
**Pull request by IamMujuziMoses**
…tion in getTracer()

Resolves https://github.com/jaegertracing/jaeger-client-java/issues/369

### CODE REVIEW

**Comment by IamMujuziMoses** [comment]
retest this please @jpkrohling

**Comment by objectiser** [comment]
@IamMujuziMoses Thank you for creating this PR - however unfortunately it does not address the problem that was outlined in the issue #369. If you could revisit that issue to understand the specific problem the issue author has raised, and then update the PR accordingly.

**Comment by pavolloffay** [comment]
I would suggest looking at UdpSender and logging the exception directly there. Do not change loggers or levels in this PR.

**Comment by pschichtel** [comment]
> I would suggest looking at UdpSender and logging the exception directly there. Do not change loggers or levels in this PR.

I took your word and actually had a look at UdpSender: https://github.com/jaegertracing/jaeger-client-java/pull/726

**Comment by pschichtel** [comment]
Since #726 is merged making the UdpSender lazy and #729 will improve the logging, I think this PR can be closed.

**Pull request closed without merging**
