### PR TITLE
Add "serialVersionUID" for exceptions to avoid InvalidClassException

### PR DESCRIPTION
**Pull request by quaff**
## Which problem is this PR solving?
avoid potential InvalidClassException when perform deserialization.

## Short description of the changes
add generated serialVersionUID for exceptions.

### CODE REVIEW

**Comment by pavolloffay** [comment]
@quaff hi, can I ask you about your serialization use case?

**Comment by quaff** [comment]
@pavolloffay please refer to https://stackoverflow.com/questions/285793/what-is-a-serialversionuid-and-why-should-i-use-it

**Comment by jpkrohling** [comment]
I don't think we'll ever need to serialize the exception (or any other class in this client, for that matter), *but*, having a serial version UID for Exceptions is indeed a good practice.

**Comment by quaff** [comment]
@jpkrohling It will used when perform RMI such as spring httpInvoker, exception will be serialized in server and deserialized in client, client rethrow it.

**Comment by pavolloffay** [comment]
@quaff thanks for the link. I am not asking why we should add serialization id, but how you are using jaeger client so you need the serialization.

**Comment by quaff** [comment]
@pavolloffay I'm using spring httpinvoker as microservice implementation, It use java serialization by default, exceptions will propagated from server to client.

**Comment by jpkrohling** [comment]
> It will used when perform RMI such as spring httpInvoker

Interesting. I wouldn't expect the client to be remotely called, or that an exception on the client library to propagate way back to a remote caller, but it would certainly make sense.

I'm curious though: is this an actual scenario you faced, or is it theoretical? If you faced this issue, would you mind sharing more details (source code would be even better). We could then derive more tests from it (cc @jkandasa)

**Comment by quaff** [comment]
The problem is not jaeger specific, but I'm using jaeger for demonstration
```
public interface EchoService {

	String echo(String message);

}

```
```
public class EchoServiceImpl implements EchoService {

	@Override
	public String echo(String message) {
		try (Scope scope = GlobalTracer.get().scopeManager().activate(GlobalTracer.get().buildSpan("echo").start(),
				true)) {
			return message;
		}
	}

}
```
```
@Component
public class Test {

	@Autowired
	private EchoService echoService;

	public void test() {
		echoService.echo("something"); // exception from server will be thrown
	}

}

```

**Comment by quaff** [comment]
@jpkrohling It's not an actual scenario, I found it because eclipse reports warning.

**Comment by jpkrohling** [comment]
Thanks @quaff !

**Pull request merged**
