### PR TITLE
Bump thrift version

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by pankaj72981** [comment]
Apache Thrift community recently released 0.14.1 due to some bug fixes. We should upgrade to 0.14.1.

**Comment by yurishkuro** [comment]
we cannot merge this until #765 is done as we have no CI to validate.

**Review by adoroszlai — CHANGES_REQUESTED** [review]
Thanks @geoand for working on this fix.  Some code change is necessary for compiling with Thrift 0.14+:

```
jaeger-thrift/src/main/java/io/jaegertracing/thrift/internal/senders/ThriftSenderBase.java:67: error: constructor AutoExpandingBufferWriteTransport in class AutoExpandingBufferWriteTransport cannot be applied to given types;
    memoryTransport = new AutoExpandingBufferWriteTransport(maxPacketSize, 2);
                      ^
  required: TConfiguration,int,int
  found: int,int
  reason: actual and formal argument lists differ in length

jaeger-thrift/src/main/java/io/jaegertracing/thrift/internal/reporters/protocols/ThriftUdpTransport.java:33: error: ThriftUdpTransport is not abstract and does not override abstract method checkReadBytesAvailable(long) in TTransport
public class ThriftUdpTransport extends TTransport implements Closeable {
       ^

2 errors

> Task :jaeger-thrift:compileJava FAILED
```

**Comment by geoand** [comment]
Oh darn.

I am afraid I don't really know much about Thift so I would just be shooting in the dark.

**Comment by yurishkuro** [comment]
fixed in #774

**Pull request closed without merging**
