### PR TITLE
Fix nexus-publish config

### PR DESCRIPTION
**Pull request by marcphilipp**
## Which problem is this PR solving?

Prior to this commit the configuration of the `nexus-publish` plugin was ineffective because it was only applied to the root project instead of all subprojects.

## Short description of the changes

Apply the nexus-publish plugin to all subprojects instead of the root
project, remove the explicitly configured repository and the default
server URLs.

### CODE REVIEW

**Comment by pavolloffay** [comment]
Sweet this worked well locally on 0.35.2. I will try from travis.

**Comment by pavolloffay** [comment]
Awesome release from travis worked - 0.35.3

**Comment by marcphilipp** [comment]
Glad it worked! 🙂

**Comment by pavolloffay** [comment]
thanks @marcphilipp !

**Pull request merged**
