### PR TITLE
Process sampling tag before handling other tags (fixes #738)

### LINKED ISSUE #738: Ignores some tags when you create a span with forced sampling
## Requirement - what kind of business use case are you trying to solve?

We have an application which we generally do not want tracing enabled, but we have certain user triggered workflows
where we'd like to enable tracing for.

The way we achieve this is for user initiated actions we build a new span (hence context) with 
`Tags.SAMPLING_PRIORITY` set to `1`, together with other tags specific to the users request.

## Problem - what in Jaeger blocks you from solving the requirement?

There is no specific order in which the tags get processed and added to the context/span, as it's an iteration over a map:

https://github.com/jaegertracing/jaeger-client-java/blob/f1a7ca91af05206b3c47573689331a1fafec16de/jaeger-core/src/main/java/io/jaegertracing/internal/JaegerSpan.java#L69-L71

This causes a problem, because tags are only set if the context is sampled

https://github.com/jaegertracing/jaeger-client-java/blob/f1a7ca91af05206b3c47573689331a1fafec16de/jaeger-core/src/main/java/io/jaegertracing/internal/JaegerSpan.java#L234-L236

But the decision whether it's sampled or not comes from one of the tags, which can arrive later (due to iteration over a map)
Hence all tags prior to the sampling tag are dropped on the floor and ignored.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

I think it should set the tags on the context unconditionally, or explicitly check for the sampling tag and do context adjustments 
before setting the rest of the tags.

## Sad workaround

Create a noop root span with sampling enabled, create a child span with actual user specific tags

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Fixes #738 
New test fails before this change.

Signed-off-by: Audrius Butkevicius <audrius.butkevicius@gmail.com>

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Any ideas of when this will be released?

**Comment by AudriusButkevicius** [comment]
Bump regarding my question.
There doesn't seem to be any information on the release cycles or when things are released. 

I want to setup a reminder to remove the current workaround we have.

**Comment by yurishkuro** [comment]
https://github.com/jaegertracing/jaeger-client-java/releases/tag/v1.4.0

**Comment by AudriusButkevicius** [comment]
Thanks!

**Comment by yurishkuro** [comment]
np

**Pull request merged**
